version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      ef:
        patterns:
          - "Microsoft.EntityFrameworkCore*"
      spectre:
        patterns:
          - "Spectre*"
      testcontainers:
        patterns:
          - "Testcontainers*"
      xunit:
        patterns:
          - "xunit*"
