name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🚧 Checkout
        uses: actions/checkout@main

      - name: 🔨 Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: ./global.json

      - name: 🏗️ Run dotnet build
        id: build
        run: dotnet build --configuration Release

      - name: 🎨 Run dotnet format
        id: format
        run: dotnet format --verbosity diagnostic --verify-no-changes --no-restore
